name: CI

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    setps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Unit test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Archive Test results
        uses: actions/upload-artifacts@v1
        with:
          name: test-report
          path: reports/test

      - name: Archive Coverage results
        uses: actions/upload-artifacts@v1
        with:
          name: coverage-report
          path: reports/coverage
